### ISSUE TITLE
CLIJ2_StatisticsOfLabelledPixelsBlock output to workbook

### ISSUE THREAD

**Issue by marionlouveaux** [clij/clicy#8]
Hi!
Currently the CLIJ2_StatisticsOfLabelledPixelsBlock generates a results window. 
Could this block have a « workbook » output (http://icy.bioimageanalysis.org/plugin/workbooks/) that could then be linked to the workbook to file block (like for the ROI Statistics block)?

Many thanks in advance!
Best regards,
Marion

**Comment by haesleinhuepf** [comment]
Hey Marion @marionlouveaux ,

what a fantastic idea. It took me a moment to figure out how Workbooks work. But then, super easy! Actually, I like a lot that Icy uses Apache Commons here instead of developing its own table format 👍  Really cool!

![image](https://user-images.githubusercontent.com/12660498/83064406-05a28e80-a062-11ea-90c2-a0e8f18335c0.png)

I'll fixe some more bugs you reported, before you can test the workfbook integration.

Thanks a lot for testing and supporting Clicy!  It's a pleasue working with you!

Cheers,
Robert

**Comment by marionlouveaux** [comment]
Hi Robert,
That's awesome :) thanks a lot for implementing this feature!!
It's a pleasure working with you too!
Cheers,
Marion
